# Generated by Django 2.1.7 on 2019-03-17 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Livro')),
                ('autor', models.CharField(default='SOBRENOME, Nome (Apenas o 1º)', max_length=120, verbose_name='Nome do autor')),
                ('genero', models.CharField(choices=[('as', 'Artes'), ('ba', 'Biologia'), ('cs', 'Ciências'), ('el', 'Espanhol'), ('fi', 'Filosofia'), ('fa', 'Física'), ('ga', 'Geografia'), ('ha', 'História'), ('ia', 'Informática'), ('is', 'Inglês'), ('ma', 'Matemática'), ('ps', 'Português'), ('qa', 'Química'), ('sa', 'Sociologia')], max_length=2, verbose_name='Gênero')),
                ('descricao', models.TextField(default='Insira uma breve descrição do livro.', verbose_name='Descrição')),
                ('lancamento', models.DateField(null=True, verbose_name='Lançamento')),
                ('arquivo', models.FileField(default='VAZIO', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_register', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.ClassRoom')),
            ],
            options={
                'abstract': False,
            },
            bases=('app_principal.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('creation', models.DateTimeField(auto_now=True)),
                ('teacher_register', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('app_principal.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='app_principal.Teacher'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_principal.Teacher'),
        ),
    ]
