# Generated by Django 2.1.7 on 2019-03-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Livro')),
                ('autor', models.CharField(default='SOBRENOME, Nome (Apenas o 1º)', max_length=120, verbose_name='Nome do autor')),
                ('genero', models.CharField(choices=[('as', 'Artes'), ('ba', 'Biologia'), ('cs', 'Ciências'), ('el', 'Espanhol'), ('fi', 'Filosofia'), ('fa', 'Física'), ('ga', 'Geografia'), ('ha', 'História'), ('ia', 'Informática'), ('is', 'Inglês'), ('ma', 'Matemática'), ('ps', 'Português'), ('qa', 'Química'), ('sa', 'Sociologia')], max_length=2, verbose_name='Gênero')),
                ('descricao', models.TextField(default='Insira uma breve descrição do livro.', verbose_name='Descrição')),
                ('lancamento', models.DateField(null=True, verbose_name='Lançamento')),
                ('arquivo', models.FileField(default='VAZIO', upload_to='')),
            ],
        ),
    ]
