# Generated by Django 2.1.7 on 2019-03-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('autor', models.CharField(default='Insira apenas o primeiro autor listado no livro.', max_length=120)),
                ('genero', models.CharField(choices=[('as', 'Artes'), ('ba', 'Biologia'), ('cs', 'Ciências'), ('el', 'Espanhol'), ('fa', 'Filosofia'), ('fa', 'Física'), ('ga', 'Geografia'), ('ha', 'História'), ('ia', 'Informática'), ('is', 'Inglês'), ('ma', 'Matemática'), ('ps', 'Português'), ('qa', 'Química'), ('sa', 'Sociologia')], max_length=2)),
                ('descricao', models.TextField(default='Insira aqui uma breve descrição do livro')),
                ('lancamento', models.DateField()),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
    ]
