# Generated by Django 2.1.7 on 2019-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=120, verbose_name='Nome completo do 1º autor listado'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(verbose_name='Insira uma breve descrição do livro.'),
        ),
    ]
