# Generated by Django 2.1.7 on 2019-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_auto_20190316_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo',
            field=models.FileField(default='VAZIO', upload_to=''),
        ),
    ]
