# Generated by Django 2.1.7 on 2019-03-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0003_livro_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='SOBRENOME, Nome (Apenas o 1º)', max_length=120),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(default='Insira uma breve descrição do livro.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('as', 'Artes'), ('ba', 'Biologia'), ('cs', 'Ciências'), ('el', 'Espanhol'), ('fa', 'Filosofia'), ('fa', 'Física'), ('ga', 'Geografia'), ('ha', 'História'), ('ia', 'Informática'), ('is', 'Inglês'), ('ma', 'Matemática'), ('ps', 'Português'), ('qa', 'Química'), ('sa', 'Sociologia')], max_length=2, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='lancamento',
            field=models.DateField(null=True, verbose_name='Lançamento'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome do Autor'),
        ),
    ]
